### ISSUE TITLE
clarification for slides 34, 36 on typeclasses w.r. neqv usage

### ISSUE THREAD

**Issue by phderome** [julien-truffaut/fp-foundation#27]
I am wondering whether the inclusion of neqv in slide 34 and its removal in slide 36 intentional.

Specifically I'd like to understand motivation of choosing between interface and record of functions. Is interface simply usage of (extensible) trait and record of functions that of a non-extensible (final) case class?

Or is the idea of defining functions in terms of other ones (e.g. neqv defined abstractly for all eqv) something that is better suited to interface over record of functions?

Additionally, usage of `case class` without `final` is rare in Scala ( and I believe it will always be final in the future); so maybe your intent was to write it as `final`.

**Comment by julien-truffaut** [comment]
Starting by the end. Yes all case classes should be `final` and all `sealed trait` should extends `Product with Serializable` but I didn't want to put too much noise because I hope to get people not familiar with scala to use this material.

I don't think think there is a fundamental difference between interface and record of function. Interface allows to have a hierarchy, default implementations but it is annoying to change a single function (you would need to create a new value and delegate all the call except the one you want to change). Record of functions make it easier to partially update it because you can use `Lens` or simply `copy` but if you want to create a hierarchy, you would need to manually copy fields.

In scala, you could have a mix. A record of functions with default implementations.

Does it answer your questions?

**Comment by phderome** [comment]
I'd suggest that the approach towards Scala features should be to embrace them to the fullest so that it's probably idiomatic even at the cost of added complexity. I don't really understand this business of `Product with Serializable` and get confused when looking at cats or scalaz libraries for method signatures encountering them. Either you ignore explaining these pesky details (because you have better things to do and emphasize) or if you find time for them, you could have some glossary section or some technical FAQ section where some of these issues are explained, time warranted.

Yes, the explanation for interface and record of functions is perfect.

In this particular instance, you may simply add the resource (it also ties with Dotty enhancements https://dotty.epfl.ch/docs/reference/new-types/union-types.html): https://typelevel.org/blog/2018/05/09/product-with-serializable.html

**Comment by julien-truffaut** [comment]
My goal is to introduce enough Scala features/details in order to discuss the FP material. If you look at the code of FP scala libraries, you will see lots of noise in order to give users best performance, type inference, etc It makes sense for a library used by many users but here I am more interested to show beautiful FP concepts as I want to encourage people to write functional code.
