### ISSUE TITLE
functorsExercises has contravariant exercises

### ISSUE THREAD

**Issue by phderome** [julien-truffaut/fp-foundation#37]
Those don't have a solution. How about removing them or simply state, that they cannot be solved?

```
// 1g. Implement a Functor instance for Predicate // f does not necessarily have an inverse and even if it did
  // cardinality of B may be much larger than that of A.
  implicit def predicateFunctor: Functor[Predicate] = new DefaultFunctor[Predicate] {
    def map[A, B](fa: Predicate[A])(f: A => B): Predicate[B] = ???
  }

  // 1h. Implement a Functor instance for StringEncoder
  implicit def stringEncoderFunctor: Functor[StringEncoder] = new DefaultFunctor[StringEncoder] {
    def map[A, B](fa: StringEncoder[A])(f: A => B): StringEncoder[B] = ???
  }
```

**Comment by julien-truffaut** [comment]
Several exercises are impossible. I use this technique to force some thinking about limitations of a concept and generally I have some slides to explain the limitations.

One way to see if an exercise is impossible to solve is to check if there is a interface for it (hence an answer). I wouldn't want to make it too obvious it is impossible to solve, otherwise it defeats the purpose but maybe we should mention it in the FAQ or somewhere else? What do you think?

**Comment by julien-truffaut** [comment]
In fact, maybe it is worth to add an exercise where you implement a `ContravariantFunctor` and another one for `InvariantFunctor`. I would still ask to first implement the `Functor` and then ask for the Contra/Invariant

**Comment by phderome** [comment]
I like that as it encourages ultimately to think about the other functors.

**Comment by julien-truffaut** [comment]
done
