### ISSUE TITLE
should test listApplicative for coherence with list as monad

### ISSUE THREAD

**Issue by phderome** [julien-truffaut/fp-foundation#41]
I implemented zip instead of cartesian product and got no error for it, though clearly my solution was not at all in line with proposed standard solution.

**Comment by julien-truffaut** [comment]
You can implement an `Apply` instance for `List` that zip the two list and it is completely fine/lawful. That's actually what 2i exercise is about. You would need an infinite list to make it an `Applicative`

There is no real rule to figure out what is the default typeclass implementation and which one is a newtype. It is generally the most "common" or in this case, I believe it is because you cannot make a `Monad` when you zip list.
